### ISSUE TITLE
Refine public API for adding addon provided steps

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-cli-yadda-opinionated#10]
Picking this up from https://repository.m2p.net/mpp/mppfrontend/merge_requests/81#note_24518:

> I split the steps in `ember-cli-yadda-opinionated` source because it's difficult to work with them when they all are in a single file. I'm even considering splitting files further as the library grows.

Agree, but that's the addon's internal structure, and here were are talking about its public API.

But as I said you can have both, and unless you export each individual step and just all given/when/then steps as a whole, I cannot see how the user is really able to pick and choose. I mean what use case could there be to pick all when steps (like without really knowing what steps they contain), but none of the then steps?

I would tend to allow `composeSteps()` as well as something like `addOptinionatedSteps()`, and eventually export each individual step maybe?

**Comment by lolmaus** [comment]
> I mean what use case could there be to pick all when steps (like without really knowing what steps they contain), but none of the then steps?

With finer grained step modules, they could, for example, include steps that interact with DOM and choose not to include steps dedicated to `ember-power-select`.

But I do agree that most users will want to simply include all steps, for which I propose this:

```js
// ember-cli-yadda-opinionated/test-support/index.js
export const opinonatedSteps= {...givenSteps, ...whenSteps, ...thenSteps};
```

```js
// my-app/tests/acceptance/my-feature-steps.js
import libraryFactory from 'my-app/tests/acceptance/steps/steps';
import { composeSteps, opinonatedSteps } from 'ember-cli-yadda-opinionated/test-support';

export default composeSteps(libraryFactory, opinonatedSteps);
```

And here's what you suggest, for comparison:

```js
// my-app/tests/acceptance/my-feature-steps.js
import libraryFactory from 'my-app/tests/acceptance/steps/steps';
import { addOptinionatedSteps } from 'ember-cli-yadda-opinionated/test-support';

export default addOptinionatedSteps(libraryFactory);
```

The difference is negligible, IMO. But what's important is that:
* The `addOptinionatedSteps`  approach is black-boxy while the `composeSteps` approach is explicit.
* The `addOptinionatedSteps` approach does not allow user control what to import and in what order:

    ```js
    // my-app/tests/acceptance/my-feature-steps.js
    import libraryFactory from 'my-app/tests/acceptance/steps/steps';
    import customSteps from 'my-app/tests/acceptance/steps/_custom-steps';
    import { composeSteps, opinonatedSteps } from 'ember-cli-yadda-opinionated/test-support';
    
    export default composeSteps(libraryFactory, opinonatedSteps, customSteps);
    ```

**Comment by simonihmig** [comment]
Approved! 

I just found it weird to have to import given/when/then separately, though that does not really provide any meaningful choice to the user. (your power-select example is a good one, but excluding power-select related steps would not be possible with the current exports anyway)
