### ISSUE TITLE
Refine public API for adding addon provided converters

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-cli-yadda-opinionated#11]
Picking this up from https://repository.m2p.net/mpp/mppfrontend/merge_requests/81#note_24511:

I still feel this could become a major PITA when this addon is used publicly, as it will provide ground for a lot of upgrade issues. Say we add a new step in a new version, that relies on a new converter. The step will probably added automatically to the app (see #10), but the user might forget adding the converter. And this will lead to weird errors (like the value pushed into the step is not converted, so just a string, and if you don't guard against that in every step using that converter, you will get type errors).

Or maybe you do some refactoring, and instead of doing some input conversion in the step, you have extracted that into a dedicated converter. When you can be sure that the new converter is available, you can make this a patch release, and the user won't even notice. If that's not the case, and the user is supposed to explicitly add the new converter, this would need a major version bump (as you cannot simply update the package without breaking things).

Beware of the cost of maintaining addons/libs, I know what I'm talking about! 😉 
@lolmaus you certainly do as well, I just want to make sure we don't fall into a trap here!

**Comment by lolmaus** [comment]
And on the other hand we have a risk of our new converter conflicting with a user-defined converter.

This conflict would happen under the hood.

For example, the user does this:

```js
const dictionary = new yadda.Dictionary();
setupDefaultSteps(dictionary);
setupOpinionatedSteps(dictionary);
setupCustomSteps(dictionary);
export dictionary;
```

And gets an error: `Error: Duplicate term: [table]` that traces deep into Yadda internals and does not point at any line of user's code.

This will cause frustration.

But if converters were defined like this: 

```js
export const dictionary = new yadda.Dictionary()
  .define('table', /([^\u0000]*)/, yadda.converters.table)  // eslint-disable-line
  .define('index', /(first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|\d+(?:st|nd|rd|th))/, indexMappingConverter)
  .define('number', /(\d+)/, yadda.converters.integer)
  .define('integer', /(\d+)/, yadda.converters.integer)
  .define('float', /([-+]?[0-9]*\.?[0-9]+)/, yadda.converters.float)
  .define('date', /(\d+)/, yadda.converters.date)
  .define('csv', /([^\u0000]*)/, csvConverter)              // eslint-disable-line
  .define('csvHash', /([^\u0000]*)/, csvHashConverter)      // eslint-disable-line
;
```

...then the error would not even happen because the issue would've been easy to notice.

**Comment by simonihmig** [comment]
> And on the other hand we have a risk of our new converter conflicting with a user-defined converter.

Sure, but we have the same risk when defining steps. And there we take that risk, and don't force the user to explicitly add each step separately!

And IMHO the upgrade (for the user) and maintainability problems (for us) outweighs the name conflict risk, AFAICT.

Maybe we should define the converters with some namespacing, to mitigate the risk? Like in our `setupOpinionatedSteps()` function provided by the addon, we do `.define('ecyo-element', REGEX_LABEL, elementConverter)` and use that in all steps (`when I click $ecyo-element`). 

If we want the user to reuse our converters by himself, we would have to document the names of those (which would be the case anyways), but then he/she needs to be explicit about where these converters come from as well. Which would be good, wouldn't it?

**Comment by lolmaus** [comment]
Ok, will do.

It would also be nice to stop depending on any external converters.
