### ISSUE TITLE
Restructure public exports

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-cli-yadda-opinionated#12]
I would suggest to move all files (except for `index.js`) in `addon-test-support` to a `-private` subfolder, to make sure nobody imports directly from them. Instead everything should be imported only from paths we explicitly declare as public API (by not having them in `-private`). Only modules reexported in `index.js` are public API.

This way we can freely refactor (e.g. create individual files for each step), without worrying about compatibility. I think this pattern is used frequently, and can be seen as best practice. E.g. https://github.com/orbitjs/ember-orbit/tree/master/addon

**Comment by lolmaus** [comment]
Agreed! 👍 

I was also thinking about this but decided to leave it for later. Glad you mentioned it.
