### ISSUE TITLE
Decouple from Ember

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-cli-yadda-opinionated#17]
This addon is only offering utils: simple functions and objects. No Ember integration is being set up.

If we decouple the addon from Ember and convert it into a regular npm package, it will become available for all JS projects, including Ember thanks to `ember-auto-import`.

One gotcha is that we'll be unable to use Ember's `require` to conditionally import modules. But if we put code that uses such modules in separate files, it shouldn't be an issue. Don't import what you don't have dependencies for, and you're good to go.

As for Mocha vs QUnit, we might not need them at all! We could still offer two versions of `composeSteps`, but in step implementations we could use Chai directly, regardless of the testing suite.

The QUnit version of `composeSteps` would log every step, and in case of a failed assertion Chai would throw a normal error. The ergonomics will be slightly worse: QUnit will not be logging successful assertions, but who needs them? And the benefit is that we would have a single compact and efficient steps library, instead of two library copies, tightly-coupled to respective test suites.

We'll also avoid testing the QUnit version of the step library, which is much harder since we'll have to mock QUnit.

@simonihmig What do you think? :D

**Comment by lolmaus** [comment]
On a second thought, half of our steps rely on `@ember/test-helpers`.

I don't see a graceful way of abstracting those away.

**Comment by simonihmig** [comment]
Agree!
