### ISSUE TITLE
Decouple from Mocha, support QUnit

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-cli-yadda-opinionated#3]

**Comment by simonihmig** [comment]
Uh, really? Maybe "second Release" milestone? 😉

**Comment by lolmaus** [comment]
Well, QUnit is four times more popular than Mocha in Ember apps and it's the official test suite of Ember.

I don't want to publicly announce `ember-cli-yadda-opinionated` while it's useless to 80% of emberistas.

**Comment by simonihmig** [comment]
Ok, so "First Release" means not an internal release, *we* can use, but something you want to announce? Then it's ok, I just thought it is not necessary for some early release we can play with internally...

**Comment by lolmaus** [comment]
Correct!

**Comment by lolmaus** [comment]
I've just realized that we don't need to *decouple* Mocha, i. e. remove it from the distro.

Since the addon is used only in the `test` environment, distro size doesn't matter!

The simplest solution is to provide two sets of imports.

Ah wait, it's the dependency on Mocha and QUnit that won't work, right? You can't have both?
