### ISSUE TITLE
Cannot find dropdown for trigger when @searchEnabled is true

### ISSUE THREAD

**Issue by dagroe** [kaliber5/ember-cli-yadda-opinionated#63]
`powerSelectFindDropdown` fails when `@searchEnabled` is set to `true` on the powerselect.

It seems `ember-power-select` removed the `listBoxId` from `aria-controls` when `@searchEnabled` is set to `true` with version `5.0.0`.
As a result the selector `powerSelectDropdownIdForTrigger` cannot find the id and `powerSelectFindDropdown` fails.

I guess I can build a workaround using the dropdown id that is still encoded in `data-ebd-id` on the trigger.

**Comment by lolmaus** [comment]
Thanks for reporting. You're welcome to start a PR!
